- name: Variables
  hosts: local
  connections: local
  Vars:
   COURSE: "DAWS with siva"
   DURATION: "5months"
   TRAINER: "Siva kumar"
  tasks: 
    name: Print Variables
    ansible.builtin.debug:
     msg: "Course is: {{ COURSE }} Trainer is: {{ SivaKumar }}"
