- name: Variables
  hosts: local
  connection: local
  vars:
   COURSE: "DAWS with siva"
   DURATION: "5months"
   TRAINER: "Siva kumar"
  tasks: 
    - name: Print Variables
      ansible.builtin.debug:
       msg: "Course is: {{ COURSE }} Trainer is: {{ TRAINER }}"