- name: demo on conditions
  hosts: local
  connection: local
  vars:
   number_of_sessions: 7
  tasks: 
  - name: sessions
    ansible.builtin.debug:
     msg: "Ansible is not more than 5 sessions"
    when: number_of_sessions < 5