- name: Demo on Loops
  hosts: local
  connection: local
  tasks:
  - name: printing list through Loops
    ansible.builtin.debug:
     msg: "Hello {{ item }}"
    loop:
     - Hanuma
     - Rama
     - Rakesh