- name: Demo on Loops
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: printing list through Loops
    ansible.builtin.package:
     name: "{{ item }}"
     state: present
    loop:
     - mysql
     - nginx
     - nodejs