- name: Demo on Loops
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: printing list through Loops
    ansible.builtin.package:
     name: "{{ item.name }}"
     state: "{{ item.state }}"
    loop:
     - { name: mysql, state: "present"}
     - { name: nginx, state: "absent"}
     - { name: nodejs, state: "absent"}